# Generated by Django 5.1.1 on 2024-09-07 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='brand',
            field=models.CharField(choices=[('Maybelline New York', 'Maybelline New York'), ('Lakme', 'Lakme'), ('Nykaa Cosmetics', 'Nykaa Cosmetics'), ('M.A.C', 'M.A.C'), ('The Face Shop', 'The Face Shop')], max_length=50),
        ),
    ]
