# Generated by Django 5.1.1 on 2024-09-24 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_products_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='inventordetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField()),
                ('pin', models.IntegerField()),
                ('phonenum', models.IntegerField()),
                ('aadharnum', models.IntegerField()),
                ('userimg', models.ImageField(upload_to='inventors')),
            ],
        ),
    ]
